### ISSUE TITLE
Support self-hosted hubots

### ISSUE THREAD

**Issue by desmondmorris** [slackapi/hubot-slack#38]
Not sure if this is the right place for this but, I am trying to deploy a hubot locally and something seems to be missing.  

The hubot appears to connect successfully:

```
root@97d32bf068fa:/usr/local/hubot# ./bin/hubot --adapter slack --name slackbot
Slack adapter options: { token: 'XXXXX',
  team: 'desmondmorris',
  name: 'slackbot',
  mode: 'blacklist',
  channels: [],
  link_names: 0 }
Successfully 'connected' as slackbot
```

I get no response from `slackbot: help` or `@slackbot: help`

Are there any limitations to self-hosting?  I omitted the "Hubot URL" in configuration, is this necessary?

**Comment by clintmiller** [comment]
I've got a similar setup where I'm not hosting Hubot on Heroku. In the Slack Hubot integration, there is no field to enter a "Hubot URL." How is this supposed to work?

**Comment by gbougeard** [comment]
Hi, I have the same issue : I deployed a containerized hubot-slack on ec2 and it cannot connect to slack.
When I run the container on my machine, the connection is done and successful.
I think it does not work on EC2 beacuse my instance might be private but as I do not see any point about how hubot-slack and slack communicate, I don't get what I miss.
Btw, there is no more Hubot URL configuration in the Slack Hubot integration.

**Comment by evansolomon** [comment]
@gbougeard this sounds like a security group egress rule issue. The client connects to Slack by a websocket, so you need to make sure the server can access the internet (this is disabled in AWS by default I think since they switched to VPCs).

**Comment by gbougeard** [comment]
Yes I finally successfully configure my security groups.
Thanks

**Comment by memelet** [comment]
Configured the security exactly how? I have opened all egress ports to 0.0.0.0 and still cannot connect to slack.
